<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Shop now__bXVsd_image_1pfbQ</name>
   <tag></tag>
   <elementGuidId>4c1eaeb2-b9b7-4b40-a159-6b85928ff1e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='CardInstance3lgSql3ApB0Oi6WCeLWkng']/div/div[2]/div/div/div/a/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.a-section.a-spacing-none._bXVsd_imgPadding_1Lkpt._bXVsd_container_1DI1V._bXVsd_block_1vI8-._bXVsd_hFull_2lnNw._bXVsd_wFull_3f8b2._bXVsd_row_3CEm0._bXVsd_itemsCenter_3flfN._bXVsd_contentCenter_3BjNx > img._bXVsd_image_1pfbQ</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ac5b5047-e4de-4382-9bde-25b8554c8596</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>The Khandavaprastha Conspiracy: a fast paced thriller that uses science and history to explain one of the deepest mysteries of the Mahabharata (Book 3 of The Mahabharata Quest series)</value>
      <webElementGuid>6124ae84-0b49-42b7-90ea-e7b3685b0718</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://m.media-amazon.com/images/I/91qI0Qv7z7L._AC_SR180,120_QL70_.jpg</value>
      <webElementGuid>514cd7fa-1414-454d-97d3-008bdd7be4ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://m.media-amazon.com/images/I/91qI0Qv7z7L._AC_SR180,120_QL70_.jpg 1x,https://m.media-amazon.com/images/I/91qI0Qv7z7L._AC_SR270,180_QL70_.jpg 1.5x,https://m.media-amazon.com/images/I/91qI0Qv7z7L._AC_SR360,240_QL70_.jpg 2x</value>
      <webElementGuid>d64e9991-e228-43cf-bad4-efec2a687642</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_bXVsd_image_1pfbQ</value>
      <webElementGuid>446d2a24-ea76-416b-95a9-0f10472956c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CardInstance3lgSql3ApB0Oi6WCeLWkng&quot;)/div[@class=&quot;_bXVsd_content_2rsXy&quot;]/div[@class=&quot;a-section a-spacing-none _bXVsd_block_1vI8- _bXVsd_row_3CEm0&quot;]/div[@class=&quot;_bXVsd_gridColumn_2Jfab&quot;]/div[@class=&quot;a-section a-spacing-none _bXVsd_container_3q4Jr _bXVsd_block_1vI8- _bXVsd_hFull_2lnNw _bXVsd_wFull_3f8b2 _bXVsd_col_358pf&quot;]/div[@class=&quot;a-section a-spacing-micro _bXVsd_productImage_1CRqz&quot;]/a[@class=&quot;a-spacing-none a-link-normal _bXVsd_link_gJc5l _bXVsd_fullSize_1_hF0 _bXVsd_hidden_L-XDK&quot;]/div[@class=&quot;a-section a-spacing-none _bXVsd_imgPadding_1Lkpt _bXVsd_container_1DI1V _bXVsd_block_1vI8- _bXVsd_hFull_2lnNw _bXVsd_wFull_3f8b2 _bXVsd_row_3CEm0 _bXVsd_itemsCenter_3flfN _bXVsd_contentCenter_3BjNx&quot;]/img[@class=&quot;_bXVsd_image_1pfbQ&quot;]</value>
      <webElementGuid>57f9f941-98f2-43f4-8180-ba5811a9b4a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CardInstance3lgSql3ApB0Oi6WCeLWkng']/div/div[2]/div/div/div/a/div/img</value>
      <webElementGuid>021c4c54-9084-48ee-84ac-8c2bfcf3f8ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='The Khandavaprastha Conspiracy: a fast paced thriller that uses science and history to explain one of the deepest mysteries of the Mahabharata (Book 3 of The Mahabharata Quest series)']</value>
      <webElementGuid>45577963-2047-42a8-8bd5-435e8fd61581</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/a/div/img</value>
      <webElementGuid>1c9aca6c-e6d8-47dd-a41f-2c524bf58722</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'The Khandavaprastha Conspiracy: a fast paced thriller that uses science and history to explain one of the deepest mysteries of the Mahabharata (Book 3 of The Mahabharata Quest series)' and @src = 'https://m.media-amazon.com/images/I/91qI0Qv7z7L._AC_SR180,120_QL70_.jpg']</value>
      <webElementGuid>3727e2b6-c86c-441d-836d-a18d591b59ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
