<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Login_Suite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>38e0b633-0b26-4de0-a33c-51ba856f8cff</testSuiteGuid>
   <testCaseLink>
      <guid>5c1799b5-d000-48ad-aca5-4be767f1831e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_Amazon_Home_Login-002</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>d3623064-6f3d-4202-bbcf-e8ded0165f42</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Data Excel</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>d3623064-6f3d-4202-bbcf-e8ded0165f42</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>mobile</value>
         <variableId>8b6801ca-b0e6-4527-bfc8-3d6e3e27f683</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>d3623064-6f3d-4202-bbcf-e8ded0165f42</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>8fd708af-a1c3-432f-8320-4b848ff43793</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
