<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Quantity</name>
   <tag></tag>
   <elementGuidId>84972945-6cf5-4e5f-98f9-a137f17f4d46</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.a-column.a-span12.a-text-left > span.a-dropdown-container > label.a-native-dropdown</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='selectQuantity']/span/div/div/span/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>47da5511-f9c8-4d62-82a9-fff59f0198e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>quantity</value>
      <webElementGuid>6ef97043-6bfb-4ade-8898-33acee4273d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-native-dropdown</value>
      <webElementGuid>1bd45c3b-ad16-4d81-9eb2-4dd9918ea480</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Quantity:</value>
      <webElementGuid>5b1e506c-414a-458d-abaa-fcee3dbf7c5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selectQuantity&quot;)/span[@class=&quot;a-declarative&quot;]/div[@class=&quot;a-row a-spacing-base&quot;]/div[@class=&quot;a-column a-span12 a-text-left&quot;]/span[@class=&quot;a-dropdown-container&quot;]/label[@class=&quot;a-native-dropdown&quot;]</value>
      <webElementGuid>5c494452-6b67-436b-bae2-ccc826e102ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='selectQuantity']/span/div/div/span/label</value>
      <webElementGuid>26c40215-f630-4c06-a878-bec4cf633343</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span/label</value>
      <webElementGuid>569a76a9-e7c3-4d50-af00-ae61e7d91c5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Quantity:' or . = 'Quantity:')]</value>
      <webElementGuid>8c874b0b-afc7-4257-8258-31e22ed5687a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
